SSEW/SSEW/urls.py
from django.contrib import admin
from django.urls import path
from home.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', home, name='home'),
    path('add_expense/', add_expense, name='add_expense'),
    path('add_fundin/', add_fund, name='add_fundin'),
    path('add_employee/', add_employee, name='add_employee'),
    path('add_inventory/', add_inventory, name='add_inventory'),
    path('report/', generate_report, name='generate_report'),
    path('ajax/load-subcategories/', load_subcategories, name='load_subcategories'),
    path('ajax/load-subsources/', load_subsources, name='load_subsources'),
    path('fund_expense_list/', fund_expense_list, name='fund_expense_list'),
    path('employee_list/', employee_list, name='employee_list'),
    path('inventory_list/', inventory_list, name='inventory_list'),
    path('all_data/', all_data, name='all_data'),
    path('admin/', admin.site.urls)
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

SSEW/home/models.py
from django.db import models

class Expenses(models.Model):
    date_time = models.DateTimeField(auto_now_add=True)
    online_expenses = models.DecimalField(max_digits=10, decimal_places=2)
    cash_expenses = models.DecimalField(max_digits=10, decimal_places=2)
    name_of_person = models.CharField(max_length=50, null=True, blank=True)
    remark = models.TextField(blank=True, null=True)
    is_employee_expense = models.BooleanField(default=False)
    employee = models.ForeignKey('Employee', on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    subcategory = models.ForeignKey('SubCategory', on_delete=models.CASCADE, default=1)

    def __str__(self):
        # If name is "Unknown" then there must be some employee, use Expenses.employee to check.
        return f"Expense Name {self.name_of_person or 'Unknown'} on {self.date_time}"


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class SubCategory(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"


class Source(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class SubSource(models.Model):
    name = models.CharField(max_length=50)
    source = models.ForeignKey(Source, related_name='subsources', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"


class FundIn(models.Model):
    date_time = models.DateTimeField(auto_now_add=True)
    online_fund = models.DecimalField(max_digits=10, decimal_places=2)
    cash_fund = models.DecimalField(max_digits=10, decimal_places=2)
    name = models.CharField(max_length=50)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    subsource = models.ForeignKey(SubSource, on_delete=models.CASCADE, default=1)
    remark = models.TextField(blank=True, null=True)
    received_by = models.ForeignKey('Employee', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"FundIn: {self.name} on {self.date_time}"


class Employee(models.Model):
    date_time = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=100)
    mobile1 = models.CharField(max_length=10)
    mobile2 = models.CharField(max_length=10, blank=True, null=True)
    aadhar_number = models.CharField(max_length=12, unique=True)
    salary = models.DecimalField(max_digits=10, decimal_places=2)
    address = models.TextField()

    def __str__(self):
        return f"{self.name}, Mob: {self.mobile1}, Aadhar: {self.aadhar_number}"


class Inventory(models.Model):
    date_time = models.DateTimeField(auto_now_add=True)
    inventory_name = models.CharField(max_length=100)
    quantity = models.PositiveIntegerField()
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    remark = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Inventory: {self.inventory_name}, Quantity: {self.quantity}, Total Price: {self.total_price}"

SSEW/home/forms.py
from django import forms
from .models import *

class ExpensesForm(forms.ModelForm):
    class Meta:
        model = Expenses
        fields = ['online_expenses', 'cash_expenses', 'name_of_person', 'remark', 'is_employee_expense', 'employee', 'category', 'subcategory']
        widgets = {
            'online_expenses': forms.NumberInput(attrs={'class': 'form-control'}),
            'cash_expenses': forms.NumberInput(attrs={'class': 'form-control'}),
            'name_of_person': forms.TextInput(attrs={'class': 'form-control'}),
            'remark': forms.TextInput(attrs={'class': 'form-control'}),
            'is_employee_expense': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'employee': forms.Select(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'subcategory': forms.Select(attrs={'class': 'form-control'}),
        }

class FundInForm(forms.ModelForm):
    class Meta:
        model = FundIn
        fields = ['online_fund', 'cash_fund', 'name', 'source', 'subsource', 'remark', 'received_by']  # Added field
        widgets = {
            'online_fund': forms.NumberInput(attrs={'class': 'form-control'}),
            'cash_fund': forms.NumberInput(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'source': forms.Select(attrs={'class': 'form-control'}),
            'subsource': forms.Select(attrs={'class': 'form-control'}),
            'remark': forms.TextInput(attrs={'class': 'form-control'}),
            'received_by': forms.Select(attrs={'class': 'form-control'}),
        }

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['name', 'mobile1', 'mobile2', 'aadhar_number', 'salary', 'address']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'mobile1': forms.TextInput(attrs={'class': 'form-control'}),
            'mobile2': forms.TextInput(attrs={'class': 'form-control'}),
            'aadhar_number': forms.TextInput(attrs={'class': 'form-control'}),
            'salary': forms.NumberInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
        }

class InventoryForm(forms.ModelForm):
    class Meta:
        model = Inventory
        fields = ['inventory_name', 'quantity', 'total_price', 'remark']
        widgets = {
            'inventory_name': forms.TextInput(attrs={'class': 'form-control'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'total_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'remark': forms.TextInput(attrs={'class': 'form-control'})
        }

SSEW/home/views.py
from .forms import *
from .models import *
from .report import *
from django.http import JsonResponse
from django.contrib import messages
from django.utils.dateparse import parse_date
from django.shortcuts import render, redirect

#Instruction : Use and pass only singular variable name throught the application.

def home(request):
    total_cash_expense = Expenses.objects.aggregate(models.Sum('cash_expenses'))['cash_expenses__sum'] or 0
    total_online_expense = Expenses.objects.aggregate(models.Sum('online_expenses'))['online_expenses__sum'] or 0
    total_cash_fund = FundIn.objects.aggregate(models.Sum('cash_fund'))['cash_fund__sum'] or 0
    total_online_fund = FundIn.objects.aggregate(models.Sum('online_fund'))['online_fund__sum'] or 0
    total_fund = total_cash_fund + total_online_fund

    total_expense = total_cash_expense + total_online_expense

    total_cash_in_hand = total_cash_fund - total_cash_expense

    # Fetch total number of employees
    total_employees = Employee.objects.count()

    # Fetch recent cash transactions (expenses and fund-ins)
    recent_cash_expense = Expenses.objects.filter(cash_expenses__gt=0).order_by('-date_time')[:2]
    recent_cash_fund_ins = FundIn.objects.filter(cash_fund__gt=0).order_by('-date_time')[:3]

    # Fetch recent online transactions (expenses and fund-ins)
    recent_online_expense = Expenses.objects.filter(online_expenses__gt=0).order_by('-date_time')[:2]
    recent_online_fund_ins = FundIn.objects.filter(online_fund__gt=0).order_by('-date_time')[:3]

    context = {
        'total_expense': total_expense,
        'total_cash_in_hand': total_cash_in_hand,
        'total_employees': total_employees,
        'recent_cash_expense': recent_cash_expense,
        'recent_cash_fund_ins': recent_cash_fund_ins,
        'recent_online_expense': recent_online_expense,
        'recent_online_fund_ins': recent_online_fund_ins,
    }
    return render(request, 'index.html', context)


def load_subcategories(request):
    category_id = request.GET.get('category')
    subcategories = SubCategory.objects.filter(category_id=category_id).all()
    return JsonResponse(list(subcategories.values('id', 'name')), safe=False)


def load_subsources(request):
    source_id = request.GET.get('source')
    subsources = SubSource.objects.filter(source_id=source_id).all()
    return JsonResponse(list(subsources.values('id', 'name')), safe=False)


def add_expense(request):
    if request.method == 'POST':
        form = ExpensesForm(request.POST)
        if form.is_valid():
            form.save()
            # To send message on Template.
            messages.success(request, 'Expense added successfully!')
            return redirect('add_expense')
    else:
        form = ExpensesForm()
    return render(request, 'add_expense.html', {'form': form})


def add_fund(request):
    if request.method == 'POST':
        form = FundInForm(request.POST)
        if form.is_valid():
            form.save()
            # To send message on Template.
            messages.success(request, 'Fund added successfully!')
            return redirect('add_fundin')
    else:
        form = FundInForm()
    return render(request, 'add_fundin.html', {'form': form})


def add_employee(request):
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = EmployeeForm()
    return render(request, 'add_employee.html', {'form': form})


def add_inventory(request):
    if request.method == 'POST':
        form = InventoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = InventoryForm()
    return render(request, 'add_inventory.html', {'form': form})


def all_data(request):
    expenses = Expenses.objects.all()
    fundin = FundIn.objects.all()
    employees = Employee.objects.all()
    inventory = Inventory.objects.all()

    context = {
        'expenses': expenses,
        'fundin': fundin,
        'employees': employees,
        'inventory': inventory,
    }
    return render(request, 'all_data.html', context)


def generate_report(request):
    from_date = request.GET.get('from_date')
    to_date = request.GET.get('to_date')
    report_type = request.GET.get('report_type')
    category_id = request.GET.get('expense_category')
    source_id = request.GET.get('fund_source')

    if from_date and to_date:
        from_date = parse_date(from_date)
        to_date = parse_date(to_date)

        if report_type == 'fund_expense_xlsx':
            return generate_fund_expense_report_xlsx(from_date, to_date)
        elif report_type == 'employee_xlsx':
            return generate_employee_report_xlsx(from_date, to_date)
        elif report_type == 'inventory_xlsx':
            return generate_inventory_report_xlsx(from_date, to_date)
        elif report_type == 'expense_category_wise_report_xlsx':
            return generate_category_wise_report_xlsx(from_date, to_date, category_id)
        elif report_type == 'fundin_source_wise_report_xlsx':
            return generate_source_wise_report_xlsx(from_date, to_date, source_id)
    else:
        return render(request, 'report.html', {'categories': Category.objects.all(), 'sources': Source.objects.all()})

SSEW/home/templates/add_employee.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/css/forms.css">
    <title>Add Employee</title>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <button onclick = "window.location.href='/'" class="btn btn-primary mb-3"> Go To Home Page </button>
                        <h2 class="card-title text-center mb-3">Add Employee</h2>
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name" class="form-label">Name</label>
                                {{ form.name }}
                            </div>
                            <div class="mb-3">
                                <label for="mobile1" class="form-label">Mobile 1</label>
                                {{ form.mobile1 }}
                            </div>
                            <div class="mb-3">
                                <label for="mobile2" class="form-label">Mobile 2</label>
                                {{ form.mobile2 }}
                            </div>
                            <div class="mb-3">
                                <label for="aadhar_number" class="form-label">Aadhar Number</label>
                                {{ form.aadhar_number }}
                            </div>
                            <div class="mb-3">
                                <label for="salary" class="form-label">Salary</label>
                                {{ form.salary }}
                            </div>
                            <div class="mb-3" id="address1">
                                <label for="address" class="form-label">Address</label>
                                {{ form.address }}
                            </div>
                            <div>
                                <button type="submit" class="btn btn-primary w-100">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

SSEW/home/templates/add_expense.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/css/forms.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Add Expense</title>
</head>

<body>
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <button onclick="window.location.href='/'" class="btn btn-primary mb-3">Go To Home Page</button>
                        <h2 class="card-title text-center mb-3">Add Expense</h2>

                        <!-- Display messages -->
                        {% if messages %}
                        <div>
                            {% for message in messages %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                            </div>
                            {% endfor %}
                        </div>
                        {% endif %}

                        
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="category" class="form-label">Category</label>
                                <span><a href="/admin/home/category/"> (Add Category) </a></span>
                                {{ form.category }}
                            </div>
                            <div class="mb-3">
                                <label for="subcategory" class="form-label">Sub-category</label>
                                <span><a href="/admin/home/subcategory/"> (Add Sub Category) </a></span>
                                {{ form.subcategory }}
                            </div>
                            <div class="mb-3">
                                <div class="form-check form-check-inline">
                                    <input type="checkbox" class="form-check-input" id="online_expense_checkbox">
                                    <label class="form-check-label" for="online_expense_checkbox">Online Expense</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input type="checkbox" class="form-check-input" id="cash_expense_checkbox">
                                    <label class="form-check-label" for="cash_expense_checkbox">Cash Expense</label>
                                </div>
                            </div>
                            <div class="mb-3" id="online_expenses" style="display: none;">
                                <label for="online_expenses" class="form-label"> Amount </label>
                                {{ form.online_expenses }}
                            </div>
                            <div class="mb-3" id="cash_expenses" style="display: none;">
                                <label for="cash_expenses" class="form-label"> Amount</label>
                                {{ form.cash_expenses }}
                            </div>
                            <div class="mb-3 form-check">
                                {{ form.is_employee_expense }}
                                <label class="form-check-label" for="id_is_employee_expense">Expense Done on
                                    Employee</label>
                            </div>
                            <div class="mb-3" id="employee-dropdown" style="display: none;">
                                <label for="employee" class="form-label">Employee</label>
                                {{ form.employee }}
                            </div>
                            <div class="mb-3" id="id_name_of_person">
                                <label for="name_of_person" class="form-label">Name of Person</label>
                                {{ form.name_of_person }}
                            </div>
                            <div class="mb-3">
                                <label for="remark" class="form-label">Remark</label>
                                {{ form.remark }}
                            </div>
                            <button type="submit" class="btn btn-primary w-100">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        document.getElementById('id_is_employee_expense').addEventListener('change', function () {
            var dropdown = document.getElementById('employee-dropdown');
            var name = document.getElementById('id_name_of_person');
            if (this.checked) {
                dropdown.style.display = 'block';
                name.style.display = 'none';
            } else {
                dropdown.style.display = 'none';
                name.style.display = 'block';
            }
        });

        $(document).ready(function () {
            $('#id_category').change(function () {
                var url = "{% url 'load_subcategories' %}";
                var categoryId = $(this).val();
                $.ajax({
                    url: url,
                    data: {
                        'category': categoryId
                    },
                    success: function (data) {
                        var subcategorySelect = $('#id_subcategory');
                        subcategorySelect.empty();
                        subcategorySelect.append('<option value="">---------</option>');
                        $.each(data, function (key, value) {
                            subcategorySelect.append('<option value="' + value.id + '">' + value.name + '</option>');
                        });
                    }
                });
            });

            $('#online_expense_checkbox').change(function () {
                if (this.checked) {
                    $('#online_expenses').show();
                    $('#cash_expenses').hide();
                    $('#cash_expense_checkbox').prop('checked', false);
                    $('#id_cash_expenses').val(0);  // Set cash expenses to 0
                } else {
                    $('#online_expenses').hide();
                }
            });

            $('#cash_expense_checkbox').change(function () {
                if (this.checked) {
                    $('#cash_expenses').show();
                    $('#online_expenses').hide();
                    $('#online_expense_checkbox').prop('checked', false);
                    $('#id_online_expenses').val(0);  // Set online expenses to 0
                } else {
                    $('#cash_expenses').hide();
                }
            });
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

SSEW/home/templates/add_fundin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/css/forms.css">
    <title>Add Fund In</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<body>
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <button onclick="window.location.href='/'" class="btn btn-primary mb-3"> Go To Home Page
                        </button>
                        <h2 class="card-title text-center mb-3">Add Fund In</h2>

                        <!-- Display messages -->
                        {% if messages %}
                        <div>
                            {% for message in messages %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                            </div>
                            {% endfor %}
                        </div>
                        {% endif %}

                        
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="source" class="form-label">Source</label>
                                <span><a href="/admin/home/source"> (Add Source) </a></span>
                                {{ form.source }}
                            </div>
                            <div class="mb-3">
                                <label for="subsource" class="form-label">Sub-Source</label>
                                <span><a href="/admin/home/subsource"> (Add Sub-Source) </a></span>
                                {{ form.subsource }}
                            </div>
                            <div class="mb-3">
                                <div class="form-check form-check-inline">
                                    <input type="checkbox" class="form-check-input" id="online_fund_checkbox">
                                    <label class="form-check-label" for="online_fund_checkbox">Online Fund</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input type="checkbox" class="form-check-input" id="cash_fund_checkbox">
                                    <label class="form-check-label" for="cash_fund_checkbox">Cash Fund</label>
                                </div>
                            </div>
                            <div class="mb-3" id="online_fund" style="display: none;">
                                <label for="online_fund" class="form-label"> Amount </label>
                                {{ form.online_fund }}
                            </div>
                            <div class="mb-3" id="cash_fund" style="display: none;">
                                <label for="cash_fund" class="form-label"> Amount </label>
                                {{ form.cash_fund }}
                            </div>
                            <div class="mb-3">
                                <label for="name" class="form-label">Name</label>
                                {{ form.name }}
                            </div>
                            <div class="mb-3">
                                <label for="received_by" class="form-label">Received By</label>
                                {{ form.received_by }}
                            </div>
                            <div class="mb-3">
                                <label for="remark" class="form-label">Remark</label>
                                {{ form.remark}}
                            </div>
                            <button type="submit" class="btn btn-primary w-100">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $('#id_source').change(function () {
                var url = "{% url 'load_subsources' %}";
                var sourceId = $(this).val();
                $.ajax({
                    url: url,
                    data: {
                        'source': sourceId
                    },
                    success: function (data) {
                        var subsourceSelect = $('#id_subsource');
                        subsourceSelect.empty();
                        subsourceSelect.append('<option value="">---------</option>');
                        $.each(data, function (key, value) {
                            subsourceSelect.append('<option value="' + value.id + '">' + value.name + '</option>');
                        });
                    }
                });
            });

            $('#online_fund_checkbox').change(function () {
                if (this.checked) {
                    $('#online_fund').show();
                    $('#cash_fund').hide();
                    $('#cash_fund_checkbox').prop('checked', false);
                    $('#id_cash_fund').val(0);  // Set cash fund to 0
                } else {
                    $('#online_fund').hide();
                    $('#id_online_fund').val(0);  // Set online fund to 0
                }
            });

            $('#cash_fund_checkbox').change(function () {
                if (this.checked) {
                    $('#cash_fund').show();
                    $('#online_fund').hide();
                    $('#online_fund_checkbox').prop('checked', false);
                    $('#id_online_fund').val(0);  // Set online fund to 0 if not checked
                } else {
                    $('#cash_fund').hide();
                    $('#id_cash_fund').val(0);  // Set cash fund to 0 if not hecked
                }
            });
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

SSEW/home/templates/add_inventory.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/css/forms.css">
    <title>Add Inventory</title>
</head>

<body>
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <button onclick = "window.location.href='/'" class="btn btn-primary mb-3"> Go To Home Page </button>
                        <h2 class="card-title text-center mb-3">Add Inventory</h2>
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="inventory_name" class="form-label">Inventory Name</label>
                                {{ form.inventory_name }}
                            </div>
                            <div class="mb-3">
                                <label for="quantity" class="form-label">Quantity</label>
                                {{ form.quantity }}
                            </div>
                            <div class="mb-3">
                                <label for="total_price" class="form-label">Total Price</label>
                                {{ form.total_price }}
                            </div>
                            <div class="mb-3">
                                <label for="remark" class="form-label">Remark</label>
                                {{ form.remark }}
                            </div>
                            <button type="submit" class="btn btn-primary w-100">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>